package db

var usernames = []string{
	"alice", "bob", "charlie", "david", "eve",
	"frank", "grace", "heidi", "ivan", "judy",
	"karl", "liam", "mallory", "niaj", "olivia",
	"peggy", "quentin", "rupert", "sybil", "trent",
	"uma", "victor", "walter", "xavier", "yvonne",
	"zara", "abby", "ben", "cleo", "derek",
	"elsa", "finn", "gwen", "hank", "isla",
	"jake", "kara", "leo", "mia", "nina",
	"oscar", "pia", "quincy", "rita", "steve",
	"tina", "ursula", "vera", "wade", "zane",
}

var titles = []string{
	"Getting Started with Go",
	"Why Simplicity Wins",
	"REST APIs in Go",
	"Understanding Pointers",
	"Goroutines Explained",
	"Error Handling Done Right",
	"Writing Clean Code",
	"Go vs Python: A Comparison",
	"Mastering the fmt Package",
	"Building a CLI Tool",
	"Concurrency in Go",
	"Working with JSON",
	"Testing Your Code",
	"Using Interfaces Effectively",
	"Dependency Management with Go Modules",
	"Structs and Methods",
	"Go for Web Development",
	"Debugging Go Programs",
	"Performance Tuning Tips",
	"Deploying Go Applications",
}

var contents = []string{
	"Go is a simple and powerful language developed by Google. This post helps you get started with Go, from installation to writing your first program.",
	"Simplicity in code leads to better maintainability and fewer bugs. Here’s why Go embraces simplicity and how you can do the same.",
	"Learn how to create a RESTful API using Go's standard `net/http` package. We cover routing, request parsing, and JSON responses.",
	"Pointers in Go are a powerful way to reference memory. This article breaks down what they are, why they matter, and how to use them.",
	"Goroutines make concurrency easy in Go. This post walks through creating goroutines and using channels to communicate safely.",
	"Error handling is critical in Go. Learn best practices, the `error` type, and how to build custom error types to improve clarity.",
	"Clean code is easy to read, change, and debug. Explore tips and idioms specific to writing clean Go code.",
	"A direct comparison of Go and Python: syntax, performance, ease of use, and use cases. Choose the right tool for the job.",
	"The `fmt` package is essential for formatting output in Go. Learn to print values, format strings, and build readable logs.",
	"CLI tools are popular in Go due to its simplicity and speed. We’ll build a small CLI app using Go’s standard libraries.",
	"Go’s concurrency model is lightweight yet powerful. Explore use cases, examples, and pitfalls in concurrent programming.",
	"Learn how to encode and decode JSON in Go using the `encoding/json` package, with tips on struct tags and custom marshaling.",
	"Testing is built into Go with the `testing` package. Learn to write table-driven tests and run benchmarks with ease.",
	"Interfaces allow flexible and decoupled code. This post dives into how interfaces work and how to design your own.",
	"Go Modules are the modern dependency system in Go. Understand `go.mod`, versioning, and how to tidy up your module tree.",
	"Structs are Go's way of grouping data. Learn how to define structs, add methods, and use them effectively in applications.",
	"Go can be used for web development too! Discover how to set up a basic web server, route requests, and serve HTML templates.",
	"Debugging Go code can be done with `delve`. Learn how to set breakpoints, inspect variables, and step through your code.",
	"Speed matters. Learn how to profile your Go app, find bottlenecks, and improve runtime performance with practical tips.",
	"From build to production, this post walks through containerizing a Go app and deploying it to the cloud using Docker and GitHub Actions.",
}

var tags = []string{
	"go",
	"golang",
	"web-development",
	"api",
	"rest",
	"concurrency",
	"pointers",
	"error-handling",
	"clean-code",
	"cli",
	"testing",
	"interfaces",
	"go-modules",
	"json",
	"performance",
	"deployment",
	"debugging",
	"goroutines",
	"programming",
	"best-practices",
}

var post_comments = []string{
	"Great explanation, really helped me understand goroutines!",
	"I was stuck on this error for hours—thanks for the clear example.",
	"Could you write a follow-up post on advanced interfaces?",
	"This is the best Go tutorial I’ve read so far.",
	"Nice article! What IDE do you recommend for Go development?",
	"I think there’s a small typo in the JSON section.",
	"Thanks! I finally understand how pointers work in Go.",
	"Awesome! Please do more posts about performance optimization.",
	"This post saved me a lot of debugging time—cheers!",
	"Can you add a downloadable version of the sample code?",
	"Love your writing style, so easy to follow!",
	"More articles like this, please!",
	"Do you have a GitHub repo for this code?",
	"I didn’t know about `go test -bench`, thanks!",
	"Can this approach work with gorilla/mux too?",
	"This makes Go look a lot less intimidating—appreciate it!",
	"I shared this with my team, super helpful.",
	"Would you recommend using this pattern in production?",
	"Subscribed to your blog right after reading this!",
	"Really clear and concise. Keep up the great work!",
}
